[stacktrace.py]
  [test_console_entry_sync_callstack[assert\]]
    expected: FAIL
