[invalid.py]
  [test_context_unknown_value]
    expected: ERROR

  [test_context_invalid_type[False\]]
    expected: ERROR

  [test_context_invalid_type[42\]]
    expected: ERROR

  [test_context_invalid_type[context3\]]
    expected: ERROR

  [test_context_invalid_type[context4\]]
    expected: ERROR
