[pointer_origin.py]
  [test_viewport_inside]
    expected: ERROR
