[invalid.py]
  [test_params_contexts_invalid_type[True\]]
    expected: FAIL

  [test_params_contexts_invalid_type[foo\]]
    expected: FAIL

  [test_params_contexts_invalid_type[42\]]
    expected: FAIL

  [test_params_contexts_invalid_type[value3\]]
    expected: FAIL

  [test_params_contexts_value_invalid_type[None\]]
    expected: FAIL

  [test_params_contexts_value_invalid_type[True\]]
    expected: FAIL

  [test_params_contexts_value_invalid_type[42\]]
    expected: FAIL

  [test_params_contexts_value_invalid_type[value3\]]
    expected: FAIL

  [test_params_contexts_value_invalid_type[value4\]]
    expected: FAIL
