[invalid.py]
  [test_params_type_invalid_value[foo\]]
    expected: ERROR

  [test_params_background_invalid_type[\]]
    expected: ERROR

  [test_params_background_invalid_type[42\]]
    expected: ERROR

  [test_params_background_invalid_type[value2\]]
    expected: ERROR

  [test_params_background_invalid_type[value3\]]
    expected: ERROR

  [test_params_user_context_invalid_type[False\]]
    expected: ERROR

  [test_params_user_context_invalid_type[42\]]
    expected: ERROR

  [test_params_user_context_invalid_type[value2\]]
    expected: ERROR

  [test_params_user_context_invalid_type[value3\]]
    expected: ERROR

  [test_params_user_context_invalid_value[\]]
    expected: ERROR

  [test_params_user_context_invalid_value[unknown\]]
    expected: ERROR

  [test_params_user_context_invalid_value_with_ref_context]
    expected: ERROR

  [test_params_user_context_removed_context]
    expected: ERROR
