[user_contexts.py]
  [test_restores_to_global_when_removed[Custom user context\]]
    expected: FAIL
