[proxy.py]
  [test_autodetect]
    expected: FAIL
