[exception_details_await_promise.py]
  [test_exception_details_await_promise[undefined-expected0\]]
    expected: FAIL

  [test_exception_details_await_promise[null-expected1\]]
    expected: FAIL

  [test_exception_details_await_promise['foobar'-expected2\]]
    expected: FAIL

  [test_exception_details_await_promise['2'-expected3\]]
    expected: FAIL

  [test_exception_details_await_promise[NaN-expected4\]]
    expected: FAIL

  [test_exception_details_await_promise[-0-expected5\]]
    expected: FAIL

  [test_exception_details_await_promise[Infinity-expected6\]]
    expected: FAIL

  [test_exception_details_await_promise[-Infinity-expected7\]]
    expected: FAIL

  [test_exception_details_await_promise[3-expected8\]]
    expected: FAIL

  [test_exception_details_await_promise[1.4-expected9\]]
    expected: FAIL

  [test_exception_details_await_promise[true-expected10\]]
    expected: FAIL

  [test_exception_details_await_promise[false-expected11\]]
    expected: FAIL

  [test_exception_details_await_promise[42n-expected12\]]
    expected: FAIL

  [test_exception_details_await_promise[(Symbol('foo'))-expected13\]]
    expected: FAIL

  [test_exception_details_await_promise[[1, 'foo', true, new RegExp(/foo/g), [1\]\]-expected14\]]
    expected: FAIL

  [test_exception_details_await_promise[({'foo': {'bar': 'baz'}, 'qux': 'quux', 1: 'fred', '2': 'thud'})-expected15\]]
    expected: FAIL

  [test_exception_details_await_promise[(()=>{})-expected16\]]
    expected: FAIL

  [test_exception_details_await_promise[(function(){})-expected17\]]
    expected: FAIL

  [test_exception_details_await_promise[(async ()=>{})-expected18\]]
    expected: FAIL

  [test_exception_details_await_promise[(async function(){})-expected19\]]
    expected: FAIL

  [test_exception_details_await_promise[(function*() { yield 'a'; })-expected20\]]
    expected: FAIL

  [test_exception_details_await_promise[new RegExp(/foo/g)-expected21\]]
    expected: FAIL

  [test_exception_details_await_promise[new Date(1654004849000)-expected22\]]
    expected: FAIL

  [test_exception_details_await_promise[new Map([[1, 2\], ['foo', 'bar'\], [true, false\], ['baz', [1\]\]\])-expected23\]]
    expected: FAIL

  [test_exception_details_await_promise[new Set([1, 'foo', true, [1\], new Map([[1,2\]\])\])-expected24\]]
    expected: FAIL

  [test_exception_details_await_promise[new WeakMap()-expected25\]]
    expected: FAIL

  [test_exception_details_await_promise[new WeakSet()-expected26\]]
    expected: FAIL

  [test_exception_details_await_promise[new Error('SOME_ERROR_TEXT')-expected27\]]
    expected: FAIL

  [test_exception_details_await_promise[[1, 2\][Symbol.iterator\]()-expected28\]]
    expected: FAIL

  [test_exception_details_await_promise['mystring'[Symbol.iterator\]()-expected29\]]
    expected: FAIL

  [test_exception_details_await_promise[(new Set([1,2\]))[Symbol.iterator\]()-expected30\]]
    expected: FAIL

  [test_exception_details_await_promise[(new Map([[1,2\]\]))[Symbol.iterator\]()-expected31\]]
    expected: FAIL

  [test_exception_details_await_promise[new Proxy({}, {})-expected32\]]
    expected: FAIL

  [test_exception_details_await_promise[(function*() { yield 'a'; })()-expected33\]]
    expected: FAIL

  [test_exception_details_await_promise[(async function*() { yield await Promise.resolve(1); })()-expected34\]]
    expected: FAIL

  [test_exception_details_await_promise[Promise.resolve()-expected35\]]
    expected: FAIL

  [test_exception_details_await_promise[new Int32Array()-expected36\]]
    expected: FAIL

  [test_exception_details_await_promise[new ArrayBuffer()-expected37\]]
    expected: FAIL

  [test_exception_details_await_promise[document.createElement('div')-expected38\]]
    expected: FAIL

  [test_exception_details_await_promise[window-expected39\]]
    expected: FAIL

  [test_exception_details_await_promise[new URL('https://example.com')-expected40\]]
    expected: FAIL
