[network_events.py]
  [test_event_order_with_redirect]
    expected: FAIL
